#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
育儿知识库扩展生成器
新增20-30篇高需求文章
生成时间：2026-02-28
"""

import json
from datetime import datetime

# 新增文章数据（30篇）
NEW_ARTICLES = [
    # ===== 睡眠专题（5篇）=====
    {
        "id": "article_051",
        "title": "宝宝夜醒频繁怎么办",
        "category": "0-6个月",
        "tags": ["睡眠", "新生儿", "夜醒"],
        "summary": "宝宝频繁夜醒影响父母休息，本文提供科学有效的应对方法。",
        "description": "宝宝夜醒频繁怎么办的详细指导，帮助父母改善宝宝睡眠质量。",
        "quickAnswers": [
            {"question": "宝宝夜醒几次算频繁？", "answer": "新生儿每2-3小时醒一次正常，3个月后夜醒>2次可能需要干预。"},
            {"question": "夜醒频繁的原因是什么？", "answer": "常见原因：饥饿、尿布湿、温度不适、睡眠联想依赖、发育跳跃期。"},
            {"question": "如何减少宝宝夜醒？", "answer": "建立固定睡前程序、白天充足活动、创造良好睡眠环境、逐步培养自主入睡能力。"},
            {"question": "需要立即回应夜醒吗？", "answer": "新生儿需要立即回应，3个月后可等待1-2分钟观察，给宝宝自我安抚机会。"},
            {"question": "什么时候需要看医生？", "answer": "伴随发热、呕吐、食欲不振、生长缓慢时需就医。"}
        ],
        "content": [
            {"type": "heading", "text": "什么是夜醒频繁"},
            {"type": "bullet", "text": "新生儿（0-3个月）：每2-3小时醒一次是正常的"},
            {"type": "bullet", "text": "婴儿（3-6个月）：夜醒1-2次正常"},
            {"type": "bullet", "text": "6个月以上：应该能连续睡6-8小时"},
            {"type": "bullet", "text": "夜醒频繁：6个月以上每晚>2次，影响睡眠质量"},
            {"type": "heading", "text": "夜醒频繁的常见原因"},
            {"type": "numbered", "text": "生理性需求：饥饿、尿布湿、温度不适（太热/太冷）"},
            {"type": "numbered", "text": "睡眠联想：需要喂奶/摇晃才能入睡（无法自主接觉）"},
            {"type": "numbered", "text": "发育跳跃期：3-4个月、6-8个月、12个月时会睡眠倒退"},
            {"type": "numbered", "text": "不适感：出牙、生病、蚊虫叮咬"},
            {"type": "numbered", "text": "过度疲劳：白天小睡不足导致晚上睡不安稳"},
            {"type": "heading", "text": "改善夜醒的方法"},
            {"type": "numbered", "text": "建立固定睡前程序：洗澡→抚触→喂奶→讲故事→关灯"},
            {"type": "numbered", "text": "白天充足活动：清醒时多趴、玩、互动（避免白天睡太多）"},
            {"type": "numbered", "text": "优化睡眠环境：室温20-22°C、湿度50-60%、遮光窗帘、白噪音"},
            {"type": "numbered", "text": "培养自主入睡：在宝宝困但清醒时放到床上，让他自己入睡"},
            {"type": "numbered", "text": "逐步减少干预：夜醒时等待1-2分钟，轻拍安抚而不是立即抱起"},
            {"type": "heading", "text": "何时需要就医"},
            {"type": "bullet", "text": "夜醒突然增多且伴随其他症状：发热、呕吐、腹泻"},
            {"type": "bullet", "text": "生长缓慢：体重、身高增长不达标"},
            {"type": "bullet", "text": "呼吸问题：打鼾、呼吸暂停、张口呼吸"},
            {"type": "info", "text": "💡 温馨提示：每个宝宝都是独特的，有些天生就是\"睡渣宝宝\"。保持耐心，持续改进睡眠习惯，大多数宝宝在6-12个月后会有明显改善。"}
        ]
    },
    {
        "id": "article_052",
        "title": "宝宝作息调整指南",
        "category": "6-12个月",
        "tags": ["作息", "睡眠", "时间表"],
        "summary": "科学规律的作息有助于宝宝健康成长，本文提供详细的作息调整方案。",
        "description": "宝宝作息混乱怎么办？本文提供科学的作息调整方法和时间表参考。",
        "quickAnswers": [
            {"question": "宝宝什么时候需要固定作息？", "answer": "3-4个月开始建立，6个月应该有相对固定的作息时间表。"},
            {"question": "理想的作息表是什么样的？", "answer": "包括：固定起床时间、规律小睡、定时喂奶、固定睡前程序、一致就寝时间。"},
            {"question": "如何调整混乱的作息？", "answer": "先固定起床时间（每天7-8点），逐步调整小睡和喂奶时间，1-2周见效。"},
            {"question": "需要严格按时吗？", "answer": "不需要精确到分钟，±30分钟弹性是合理的，重点是保持顺序一致。"},
            {"question": "作息调整需要多长时间？", "answer": "通常需要1-2周，前3天可能最难，宝宝会抗拒，坚持就会见效。"}
        ],
        "content": [
            {"type": "heading", "text": "作息混乱的表现"},
            {"type": "bullet", "text": "白天睡觉时间不固定，有时睡1小时，有时睡3小时"},
            {"type": "bullet", "text": "晚上睡觉时间不规律，有时8点睡，有时11点睡"},
            {"type": "bullet", "text": "白天和夜晚颠倒，白天睡得多，晚上精神好"},
            {"type": "bullet", "text": "喂奶时间混乱，没有固定间隔"},
            {"type": "heading", "text": "各年龄段理想作息表"},
            {"type": "heading", "text": "3-6个月作息表"},
            {"type": "bullet", "text": "7:00 起床 + 喂奶"},
            {"type": "bullet", "text": "9:00-10:00 小睡（1-1.5小时）"},
            {"type": "bullet", "text": "12:00 喂奶 + 午睡（1.5-2小时）"},
            {"type": "bullet", "text": "15:00-16:00 小睡（1小时）"},
            {"type": "bullet", "text": "18:00 喂奶"},
            {"type": "bullet", "text": "19:00-19:30 睡前程序（洗澡→抚触→喂奶）"},
            {"type": "bullet", "text": "20:00 就寝"},
            {"type": "heading", "text": "6-12个月作息表"},
            {"type": "bullet", "text": "7:00 起床 + 早餐（奶+辅食）"},
            {"type": "bullet", "text": "9:30-10:30 小睡（1-1.5小时）"},
            {"type": "bullet", "text": "12:00 午餐（辅食+奶）"},
            {"type": "bullet", "text": "13:00-15:00 午睡（2小时）"},
            {"type": "bullet", "text": "15:30 加餐（水果/零食）"},
            {"type": "bullet", "text": "18:00 晚餐（辅食）"},
            {"type": "bullet", "text": "19:00 喂奶 + 睡前程序"},
            {"type": "bullet", "text": "20:00 就寝"},
            {"type": "heading", "text": "作息调整5步法"},
            {"type": "numbered", "text": "固定起床时间：每天同一时间叫醒宝宝（即使他睡得很晚），推荐7-8点"},
            {"type": "numbered", "text": "记录当前作息：观察3天，记录宝宝自然睡眠和饮食时间"},
            {"type": "numbered", "text": "制定目标作息：根据宝宝月龄，制定理想作息表"},
            {"type": "numbered", "text": "逐步调整：每天调整15-30分钟，不要一次性大幅改变"},
            {"type": "numbered", "text": "坚持1-2周：前3天最难，宝宝可能抗拒，但坚持就会见效"},
            {"type": "heading", "text": "作息调整注意事项"},
            {"type": "bullet", "text": "周末也要保持作息：不要因为是周末就放松要求"},
            {"type": "bullet", "text": "允许±30分钟弹性：不需要精确到分钟，保持顺序一致更重要"},
            {"type": "bullet", "text": "生病时暂停：宝宝生病时暂停作息训练，恢复后继续"},
            {"type": "bullet", "text": "睡前程序很重要：固定的睡前程序帮助宝宝建立睡眠联想"},
            {"type": "info", "text": "⚠️ 注意：作息调整不是一蹴而就的，需要父母的耐心和坚持。通常1-2周后会看到明显改善。"}
        ]
    },
    {
        "id": "article_053",
        "title": "宝宝白天睡眠时长标准",
        "category": "0-6个月",
        "tags": ["小睡", "睡眠时长", "白天睡眠"],
        "summary": "宝宝白天应该睡多久？各年龄段睡眠时长标准详解。",
        "description": "宝宝白天睡多久正常？本文提供各月龄段白天睡眠时长标准和判断方法。",
        "quickAnswers": [
            {"question": "新生儿白天要睡多久？", "answer": "新生儿白天总睡眠14-17小时，分布3-5次小睡，每次2-3小时。"},
            {"question": "3个月宝宝白天睡几次？", "answer": "3-4次，每次1.5-2小时，总睡眠时间约4-5小时。"},
            {"question": "6个月宝宝白天还需要几次小睡？", "answer": "2-3次，上午1.5-2小时，下午1-1.5小时，傍晚30-45分钟。"},
            {"question": "宝宝白天睡太多晚上不睡怎么办？", "answer": "减少白天小睡时长，最后一次小睡不要超过下午5点，增加白天活动量。"},
            {"question": "如何判断宝宝白天睡够了？", "answer": "醒来后精神好、情绪稳定、食欲正常，说明睡眠充足。"}
        ],
        "content": [
            {"type": "heading", "text": "各月龄白天睡眠标准"},
            {"type": "heading", "text": "0-3个月（新生儿期）"},
            {"type": "bullet", "text": "总睡眠时间：14-17小时/24小时"},
            {"type": "bullet", "text": "白天小睡：3-5次，每次2-3小时"},
            {"type": "bullet", "text": "白天总睡眠：约8-10小时"},
            {"type": "bullet", "text": "清醒时间：每次1-1.5小时"},
            {"type": "heading", "text": "3-6个月"},
            {"type": "bullet", "text": "总睡眠时间：14-16小时/24小时"},
            {"type": "bullet", "text": "白天小睡：3-4次，每次1.5-2小时"},
            {"type": "bullet", "text": "白天总睡眠：约4-5小时"},
            {"type": "bullet", "text": "清醒时间：每次1.5-2小时"},
            {"type": "heading", "text": "6-9个月"},
            {"type": "bullet", "text": "总睡眠时间：14小时/24小时"},
            {"type": "bullet", "text": "白天小睡：2-3次"},
            {"type": "bullet", "text": "上午小睡：1.5-2小时"},
            {"type": "bullet", "text": "下午小睡：1-1.5小时"},
            {"type": "bullet", "text": "傍晚小睡：30-45分钟（可选）"},
            {"type": "bullet", "text": "清醒时间：每次2-2.5小时"},
            {"type": "heading", "text": "9-12个月"},
            {"type": "bullet", "text": "总睡眠时间：13-14小时/24小时"},
            {"type": "bullet", "text": "白天小睡：2次"},
            {"type": "bullet", "text": "上午小睡：1.5-2小时"},
            {"type": "bullet", "text": "下午小睡": "1-1.5小时"},
            {"type": "bullet", "text": "清醒时间：每次2.5-3小时"},
            {"type": "heading", "text": "判断宝宝是否睡够的信号"},
            {"type": "heading", "text": "睡够了的表现 ✅"},
            {"type": "bullet", "text": "醒来后精神饱满，情绪愉快"},
            {"type": "bullet", "text": "食欲正常，吃奶/辅食有胃口"},
            {"type": "bullet", "text": "白天活动时专注、好奇"},
            {"type": "bullet", "text": "晚上入睡容易，夜醒少"},
            {"type": "heading", "text": "睡眠不足的表现 ❌"},
            {"type": "bullet", "text": "醒来后哭闹、烦躁"},
            {"type": "bullet", "text": "食欲下降，不愿意吃"},
            {"type": "bullet", "text": "白天过度活跃，难以安抚"},
            {"type": "bullet", "text": "晚上入睡困难，频繁夜醒"},
            {"type": "bullet", "text": "揉眼睛、打哈欠（过度疲劳）"},
            {"type": "heading", "text": "白天睡眠常见问题"},
            {"type": "heading", "text": "问题1：白天睡太多，晚上不睡"},
            {"type": "bullet", "text": "解决方案：缩短小睡时长（最多2小时/次）"},
            {"type": "bullet", "text": "最后一次小睡不要晚于下午5点"},
            {"type": "bullet", "text": "增加白天活动量，多趴、多玩"},
            {"type": "heading", "text": "问题2：白天睡太少，过度疲劳"},
            {"type": "bullet", "text": "解决方案：观察睡眠信号（揉眼、打哈欠、目光呆滞）"},
            {"type": "bullet", "text": "及时哄睡，不要等到宝宝哭闹"},
            {"type": "bullet", "text": "创造安静的睡眠环境"},
            {"type": "heading", "text": "问题3：小睡时间太短"},
            {"type": "bullet", "text": "解决方案：延长白天的喂奶间隔，确保饥饿不是原因"},
            {"type": "bullet", "text": "使用白噪音遮盖干扰声音"},
            {"type": "bullet", "text": "接觉：小睡30分钟时轻拍安抚，帮助接续睡眠"},
            {"type": "info", "text": "💡 关键原则：每个宝宝睡眠需求不同，观察宝宝的睡眠信号和精神状态，比严格遵循时间表更重要。"}
        ]
    },
    {
        "id": "article_054",
        "title": "宝宝睡回笼觉要叫醒吗",
        "category": "6-12个月",
        "tags": ["小睡", "作息", "叫醒"],
        "summary": "宝宝白天睡太晚，要不要叫醒？如何平衡白天小睡和晚上睡眠？",
        "description": "宝宝睡回笼觉要叫醒吗？本文详细分析叫醒宝宝的时机和方法。",
        "quickAnswers": [
            {"question": "宝宝白天睡太久要叫醒吗？", "answer": "下午5点后的小睡建议叫醒，否则会影响晚上入睡。"},
            {"question": "如何判断小睡时间太长？", "answer": "单次小睡超过2.5小时，或下午5点后还在睡，建议叫醒。"},
            {"question": "叫醒宝宝会让他哭闹怎么办？", "answer": "温柔叫醒：轻声说话、轻拍身体、拉开窗帘，给他5-10分钟慢慢醒来。"},
            {"question": "晚上睡不好是因为白天睡太多吗？", "answer": "是的，白天总睡眠超过4-5小时，或太晚睡，都会影响晚上睡眠质量。"},
            {"question": "什么时候不需要叫醒？", "answer": "中午12点-3点之间的午睡不需要叫醒，这是最重要的休息时间。"}
        ],
        "content": [
            {"type": "heading", "text": "为什么需要叫醒宝宝"},
            {"type": "bullet", "text": "保护晚上睡眠：白天睡太多或太晚会影响晚上入睡时间和质量"},
            {"type": "bullet", "text": "维持作息规律：固定起床和就寝时间，建立生物钟"},
            {"type": "bullet", "text": "确保足够清醒时间：宝宝需要足够的清醒时间来消耗体力，晚上才能睡好"},
            {"type": "bullet", "text": "避免昼夜颠倒：白天睡太多会导致晚上精神好，形成恶性循环"},
            {"type": "heading", "text": "需要叫醒的情况"},
            {"type": "numbered", "text": "下午5点后的小睡：无论睡了多久，5点后建议叫醒"},
            {"type": "numbered", "text": "单次小睡超过2.5小时：小睡太长会影响下一次小睡和晚上睡眠"},
            {"type": "numbered", "text": "白天总睡眠超过5小时：对于6个月以上宝宝，白天总睡眠不应超过5小时"},
            {"type": "numbered", "text": "接近晚上喂奶时间：如果小睡影响晚上喂奶时间，需要叫醒"},
            {"type": "heading", "text": "不需要叫醒的情况"},
            {"type": "numbered", "text": "生病时：生病时宝宝需要更多睡眠来恢复，不要叫醒"},
            {"type": "numbered", "text": "生长发育期：猛长期（3-6周、3-6个月）可能需要更多睡眠"},
            {"type": "numbered", "text": "中午12-3点的午睡：这是最重要的休息时间，可以让宝宝自然醒"},
            {"type": "numbered", "text": "晚上睡眠不足：如果前一天晚上睡得少，白天可以多睡会补觉"},
            {"type": "heading", "text": "温柔叫醒的方法"},
            {"type": "numbered", "text": "提前10分钟开始准备：不要等到最后一刻突然叫醒"},
            {"type": "numbered", "text": "轻声说话：用温柔的声音叫宝宝的名字，说\"起床啦\""},
            {"type": "numbered", "text": "轻拍身体：轻拍宝宝的背、手臂或腿，逐渐增加力度"},
            {"type": "numbered", "text": "拉开窗帘：让自然光线进入房间，帮助唤醒"},
            {"type": "numbered", "text": "调节温度：稍微降低室温，用凉爽的空气唤醒"},
            {"type": "numbered", "text": "给予5-10分钟过渡期：给宝宝时间慢慢清醒，不要立即抱起"},
            {"type": "heading", "text": "叫醒后的安抚"},
            {"type": "bullet", "text": "拥抱和安抚：叫醒后给宝宝一个大大的拥抱，轻声安抚"},
            {"type": "bullet", "text": "提供食物：叫醒后立即喂奶或提供辅食，缓解饥饿带来的烦躁"},
            {"type": "bullet", "text": "换尿布：更换干爽的尿布，让宝宝感到舒适"},
            {"type": "bullet", "text": "玩耍互动：用玩具、说话吸引宝宝的注意力，转换情绪"},
            {"type": "heading", "text": "常见问题"},
            {"type": "heading", "text": "问题1：叫醒后哭闹不止"},
            {"type": "bullet", "text": "原因：没睡够、叫醒方式太突然、身体不适"},
            {"type": "bullet", "text": "解决：下次提前5-10分钟开始温柔叫醒，检查是否生病"},
            {"type": "heading", "text": "问题2：叫醒后不肯起床"},
            {"type": "bullet", "text": "原因：困倦、没睡够、起床气"},
            {"type": "bullet", "text": "解决：给他5-10分钟躺床上，播放轻音乐，慢慢清醒"},
            {"type": "heading", "text": "问题3：叫醒后不吃不喝"},
            {"type": "bullet", "text": "原因：还没完全清醒、情绪不好"},
            {"type": "bullet", "text": "解决：等待10-15分钟再喂，先玩耍转移注意力"},
            {"type": "info", "text": "💡 记住：叫醒宝宝是为了保护晚上睡眠，所以需要温柔但坚定。保持一致性，让宝宝习惯作息规律。"}
        ]
    },
    {
        "id": "article_055",
        "title": "宝宝自主入睡培养",
        "category": "6-12个月",
        "tags": ["自主入睡", "睡眠训练", "独立睡眠"],
        "summary": "如何让宝宝学会自己入睡？本文提供科学的自主入睡培养方法。",
        "description": "宝宝自主入睡培养指南，帮助宝宝建立健康的睡眠习惯。",
        "quickAnswers": [
            {"question": "什么时候开始培养自主入睡？", "answer": "4-6个月是最佳时机，宝宝已经具备自我安抚能力。"},
            {"question": "什么是自主入睡？", "answer": "宝宝在困但清醒的状态下放到床上，不需要喂奶、摇晃就能自己入睡。"},
            {"question": "如何培养自主入睡？", "answer": "建立固定睡前程序、在困但清醒时放到床上、逐步减少干预、保持一致性。"},
            {"question": "需要哭声控制法吗？", "answer": "不一定。可以采用渐进式方法：抱起→放下法，逐步安抚到轻拍再到观察。"},
            {"question": "多久能见效？", "answer": "通常需要1-2周，前3天最难，宝宝会哭闹抗议，坚持就会见效。"}
        ],
        "content": [
            {"type": "heading", "text": "什么是自主入睡"},
            {"type": "bullet", "text": "定义：宝宝在困但清醒的状态下放到床上，自己入睡"},
            {"type": "bullet", "text": "不需要：喂奶、摇晃、拍睡、父母陪伴"},
            {"type": "bullet", "text": "能够：夜醒后自己接觉，不需要父母干预"},
            {"type": "bullet", "text": "好处：宝宝和父母都能睡整夜，减少睡眠剥夺"},
            {"type": "heading", "text": "自主入睡的前置条件"},
            {"type": "numbered", "text": "月龄≥4个月：宝宝具备自我安抚能力"},
            {"type": "numbered", "text": "健康良好：无疾病、不适（出牙、生病暂停训练）"},
            {"type": "numbered", "text": "体重达标：出生体重≥2倍，或≥6kg"},
            {"type": "numbered", "text": "固定作息：有规律的作息和睡前程序"},
            {"type": "heading", "text": "培养自主入睡的5个步骤"},
            {"type": "heading", "text": "步骤1：建立固定睡前程序"},
            {"type": "bullet", "text": "每天同一时间开始（如晚上7点）"},
            {"type": "bullet", "text": "顺序一致：洗澡→抚触→穿睡袋→喂奶→讲故事→关灯"},
            {"type": "bullet", "text": "时长30-45分钟：给宝宝足够时间放松和准备睡眠"},
            {"type": "bullet", "text": "安静、温馨：避免刺激性的玩具和游戏"},
            {"type": "heading", "text": "步骤2：观察睡眠信号"},
            {"type": "bullet", "text": "揉眼睛、揉脸"},
            {"type": "bullet", "text": "打哈欠"},
            {"type": "bullet", "text": "目光呆滞、眼神不集中"},
            {"type": "bullet", "text": "活动减少、变安静"},
            {"type": "bullet", "text": "拉耳朵、挠头"},
            {"type": "info", "text": "⏰ 最佳时机：宝宝困但还清醒时，这是放床的最佳时机！"},
            {"type": "heading", "text": "步骤3：在困但清醒时放到床上"},
            {"type": "bullet", "text": "不要等到睡着：在宝宝困但还清醒时放到床上"},
            {"type": "bullet", "text": "不要喂奶到睡：喂奶和睡觉分开，避免形成睡眠联想"},
            {"type": "bullet", "text": "放到婴儿床：不是父母的大床，建立独立睡眠空间"},
            {"type": "heading", "text": "步骤4：逐步减少干预"},
            {"type": "heading", "text": "第1-3天：抱起→放下法"},
            {"type": "bullet", "text": "宝宝哭闹时，立即抱起安抚"},
            {"type": "bullet", "text": "安静下来后，立即放回床上"},
            {"type": "bullet", "text": "重复多次，直到宝宝自己入睡"},
            {"type": "heading", "text": "第4-7天：椅子法"},
            {"type": "bullet", "text": "坐在床边，不抱起宝宝"},
            {"type": "bullet", "text": "用言语和轻拍安抚"},
            {"type": "bullet", "text": "逐步拉远距离：床边→门口→门外"},
            {"type": "heading", "text": "第8-14天：渐进式等待"},
            {"type": "bullet", "text": "宝宝哭闹时，等待1-2分钟再进入房间"},
            {"type": "bullet", "text": "轻声安抚、轻拍，不抱起"},
            {"type": "bullet", "text": "逐步延长等待时间：2分钟→5分钟→10分钟"},
            {"type": "heading", "text": "步骤5：夜醒时的处理"},
            {"type": "bullet", "text": "等待1-2分钟：给宝宝自我安抚的机会"},
            {"type": "bullet", "text": "检查基本需求：尿布、温度、生病"},
            {"type": "bullet", "text": "不要喂奶：除非是真正的饥饿（间隔≥4小时）"},
            {"type": "bullet", "text": "快速安抚：轻拍、言语，不抱起"},
            {"type": "heading", "text": "常见问题"},
            {"type": "heading", "text": "问题1：训练3天没效果"},
            {"type": "bullet", "text": "正常现象：前3天是最难的，宝宝会哭闹抗议"},
            {"type": "bullet", "text": "继续坚持：通常在第5-7天看到改善"},
            {"type": "bullet", "text": "检查一致性：确保每次都用同样的方法"},
            {"type": "heading", "text": "问题2：宝宝哭得很厉害"},
            {"type": "bullet", "text": "暂停训练：如果宝宝哭得无法安抚，暂停几天"},
            {"type": "bullet", "text": "调整方法：采用更温和的方法，如抱起→放下法"},
            {"type": "bullet", "text": "检查原因：生病、出牙、发育跳跃期都可能导致睡眠倒退"},
            {"type": "heading", "text": "问题3：训练成功后又倒退"},
            {"type": "bullet", "text": "常见原因：生病、出牙、发育跳跃期、旅行、作息改变"},
            {"type": "bullet", "text": "恢复训练：回到原来的方法，通常3-5天恢复"},
            {"type": "info", "text": "💡 温馨提示：自主入睡训练需要父母有很大的耐心和毅力。前3天是最难的，但坚持下来，宝宝和父母都能享受更好的睡眠。如果2周后仍无改善，建议咨询儿科医生或睡眠专家。"}
        ]
    },
    # ===== 喂养专题（5篇）=====
    {
        "id": "article_056",
        "title": "宝宝奶量标准表",
        "category": "0-6个月",
        "tags": ["奶量", "喂养", "标准"],
        "summary": "宝宝每天应该喝多少奶？各月龄奶量标准参考表。",
        "description": "宝宝奶量标准表，提供各月龄段每天和每次的奶量参考。",
        "quickAnswers": [
            {"question": "新生儿每次喝多少奶？", "answer": "初生儿每次15-30ml，1周后60-90ml，1个月后90-120ml。"},
            {"question": "宝宝每天应该喝多少奶？", "answer": "新生儿每天600-800ml，3个月800-1000ml，6个月800-1000ml（含辅食）。"},
            {"question": "如何判断宝宝吃饱了？", "answer": "吞咽声明显、满足地松开乳头/奶瓶、体重正常增长、每天6片以上湿尿布。"},
            {"question": "宝宝奶量不够怎么办？", "answer": "增加喂养频率、检查奶嘴流速、确保衔乳正确、咨询医生是否需要补充奶粉。"},
            {"question": "宝宝奶量太多会撑坏吗？", "answer": "健康的宝宝会自己控制食量，吃多了会吐出来。但过度喂养可能导致肥胖和消化不良。"}
        ],
        "content": [
            {"type": "heading", "text": "各月龄奶量标准表"},
            {"type": "heading", "text": "0-1个月（新生儿期）"},
            {"type": "bullet", "text": "第1天：每次5-7ml（初乳）"},
            {"type": "bullet", "text": "第3天：每次15-30ml"},
            {"type": "bullet", "text": "第7天：每次60-90ml"},
            {"type": "bullet", "text": "每天总奶量：600-800ml"},
            {"type": "bullet", "text": "喂养频率：每2-3小时一次，每天8-12次"},
            {"type": "heading", "text": "1-3个月"},
            {"type": "bullet", "text": "每次奶量：90-120ml"},
            {"type": "bullet", "text": "每天总奶量：700-900ml"},
            {"type": "bullet", "text": "喂养频率：每3-4小时一次，每天7-9次"},
            {"type": "bullet", "text": "夜间喂养：可能还需要1-2次夜奶"},
            {"type": "heading", "text": "3-6个月"},
            {"type": "bullet", "text": "每次奶量：120-180ml"},
            {"type": "bullet", "text": "每天总奶量：800-1000ml"},
            {"type": "bullet", "text": "喂养频率：每4-5小时一次，每天6-8次"},
            {"type": "bullet", "text": "夜间喂养：部分宝宝可以断夜奶"},
            {"type": "heading", "text": "6-12个月（添加辅食后）"},
            {"type": "bullet", "text": "每次奶量：180-240ml"},
            {"type": "bullet", "text": "每天总奶量：600-800ml"},
            {"type": "bullet", "text": "喂养频率：每天3-4次奶 + 3次辅食"},
            {"type": "bullet", "text": "夜间喂养：大部分可以断夜奶"},
            {"type": "heading", "text": "判断宝宝吃饱的信号"},
            {"type": "heading", "text": "吃饱了的表现 ✅"},
            {"type": "bullet", "text": "吞咽声明显：每吸吮几次能听到明显的吞咽声"},
            {"type": "bullet", "text": "满足地松开：主动松开乳头或奶瓶，表情满足"},
            {"type": "bullet", "text": "体重增长：每周增加150-250g，每月增加600-1000g"},
            {"type": "bullet", "text": "尿布湿透：每天至少6片湿透的尿布"},
            {"type": "bullet", "text": "大便正常：母乳宝宝每天3-4次软便，奶粉宝宝每天1-2次"},
            {"type": "heading", "text": "没吃饱的表现 ❌"},
            {"type": "bullet", "text": "吸吮不停：吃完还哭，找奶吃"},
            {"type": "bullet", "text": "体重增长慢：连续2周体重增长不达标"},
            {"type": "bullet", "text": "尿布少：每天少于4片湿尿布"},
            {"type": "bullet", "text": "大便少或干：排便次数减少，大便干燥"},
            {"type": "bullet", "text": "哭闹不安：表现出饥饿的哭声"},
            {"type": "heading", "text": "奶量异常的应对"},
            {"type": "heading", "text": "情况1：奶量不足"},
            {"type": "bullet", "text": "原因：母乳不足、奶嘴流速慢、宝宝吸吮力弱"},
            {"type": "bullet", "text": "解决方案：增加喂养频率、更换奶嘴孔径、确保正确衔乳、咨询医生补充奶粉"},
            {"type": "heading", "text": "情况2：奶量过多"},
            {"type": "bullet", "text": "表现：每次吃奶后吐奶、体重增长过快"},
            {"type": "bullet", "text": "解决方案：控制单次奶量、增加喂养频率但减少量、避免强迫喂食"},
            {"type": "heading", "text": "情况3：突然不吃奶"},
            {"type": "bullet", "text": "原因：生病、出牙、厌奶期、环境影响"},
            {"type": "bullet", "text": "解决方案：检查是否生病、尝试不同姿势、减少干扰、保持耐心（厌奶期通常1-2周）"},
            {"type": "info", "text": "💡 重要提醒：每个宝宝的需求不同，以上数据是参考范围。观察宝宝的生长发育曲线和精神状态，比严格遵循数据更重要。"}
        ]
    },
    {
        "id": "article_057",
        "title": "宝宝拒奶瓶解决方案",
        "category": "6-12个月",
        "tags": ["拒奶瓶", "奶瓶", "喂养"],
        "summary": "宝宝突然不肯用奶瓶怎么办？提供实用的解决方案。",
        "description": "宝宝拒奶瓶怎么办？本文分析原因并提供5种实用的解决方法。",
        "quickAnswers": [
            {"question": "宝宝为什么拒绝奶瓶？", "answer": "常见原因：奶嘴流速不合适、不喜欢奶嘴材质、习惯母乳衔乳、生病不适、环境干扰。"},
            {"question": "如何让宝宝接受奶瓶？", "answer": "选择合适的奶嘴、在宝宝饿但不饿急时尝试、由其他人喂奶、保持安静环境、逐步过渡。"},
            {"question": "需要更换哪些奶嘴？", "answer": "尝试不同形状（扁形、圆形）、不同材质（硅胶、乳胶）、不同流速的奶嘴。"},
            {"question": "宝宝拒绝奶瓶会饿坏吗？", "answer": "健康的宝宝不会让自己饿坏。可以尝试杯子、勺子喂奶，或暂时增加母乳喂养。"},
            {"question": "什么时候需要看医生？", "answer": "如果宝宝完全拒食超过24小时、伴随发热、呕吐、体重下降，需立即就医。"}
        ],
        "content": [
            {"type": "heading", "text": "宝宝拒绝奶瓶的常见原因"},
            {"type": "numbered", "text": "奶嘴问题：流速太快/太慢、材质不喜欢、形状不合适"},
            {"type": "numbered", "text": "衔乳习惯：习惯了母乳的触感和温度，奶嘴感觉陌生"},
            {"type": "